server:
  servlet:
    encoding:
      charset: utf-8 # 톰캣이 br,bw 할때 3Byte로 끊어 읽는 다는 것
      force: true
    session:
      timeout: 30m # 톰캣이 세션을 만드니까 톰캣이 세팅함(request도 마찬가지)
  port: 8080 # 스프링 들어오기전 톰캣의 포트

spring: # 톰캣을 통과해서 스프링으로 옴
  mustache:
    servlet:
      expose-session-attributes: true
      expose-request-attributes: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL
    username: sa
    password:
  h2:
    console:
      enabled: true
#  sql: # 아무것도 안적혀있어서 오류가 나니까 주석처리 되어 있음
#    init:
#      data-locations:
#        - classpath:db/data.sql
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true